name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore GamesManager.sln
    - name: Build
      run: dotnet build GamesManager.sln --configuration Release --no-restore
    - name: Domain Test
      run: dotnet test "Tests\Games.Domain.Tests\Games.Domain.Tests.csproj"  --no-restore --verbosity minimal
    - name: Infrastructure Test
      run: dotnet test "Tests\Games.Infrastructure.Tests\Games.Infrastructure.Tests.csproj"--no-restore --verbosity minimal
    - name: Application Test
      run: dotnet test "Tests\Games.Application.UnitTests\Games.Application.UnitTests.csproj"  --no-restore --verbosity minimal
